### ISSUE TITLE
点击开始没有反应

### ISSUE THREAD

**Issue by hllhe** [rencaa/jiujia#1]
如何使用

**Comment by rencaa** [comment]
约苗九价订阅扫描 使用步骤：

1登陆电脑微信 2关注微信公众号（约苗）

3配置fd抓包 4在公众号（疫苗预约）打开 抓取如下的包

tk: wxtoken:f9bd4e1a111df01c530a79b30063f9c6_0ef94d2f3ffbb43b470c6663291c3d97

**Comment by hllhe** [comment]
首先感谢大佬的回复，我获取了tk，fd也抓好了，点击开始还是没有反应，运行状态空白未显示


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "rencaa/jiujia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 上午8:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rencaa/jiujia] 点击开始没有反应 (Issue #1)





 
约苗九价订阅扫描 使用步骤：
 
1登陆电脑微信 2关注微信公众号（约苗）
 
3配置fd抓包 4在公众号（疫苗预约）打开 抓取如下的包
 
tk: wxtoken:f9bd4e1a111df01c530a79b30063f9c6_0ef94d2f3ffbb43b470c6663291c3d97

**Comment by hllhe** [comment]
老哥我的情况给你附件了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rencaa/jiujia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 上午8:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rencaa/jiujia] 点击开始没有反应 (Issue #1)





 
约苗九价订阅扫描 使用步骤：
 
1登陆电脑微信 2关注微信公众号（约苗）
 
3配置fd抓包 4在公众号（疫苗预约）打开 抓取如下的包
 
tk: wxtoken:f9bd4e1a111df01c530a79b30063f9c6_0ef94d2f3ffbb43b470c6663291c3d97

**Comment by rencaa** [comment]
现在只是TK  好像不行了 要类似这一段了
Host: wx.scmttec.com
Connection: keep-alive
Accept: application/json, text/plain, */*
tk: wxtoken:f9bd4e1a111df01c530a79b30063f9c6_0ef94d2f3ffbb43b470c6663291c3d97
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 NetType/WIFI MicroMessenger/7.0.20.1781(0x6700143B) WindowsWechat(0x63060012)
st: af813f3b3ae8ae30da42bcab610c602e

**Comment by hllhe** [comment]
这一段tk需要怎么抓包，fd还是哪里呢？谢谢


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月19日(周二) 下午3:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rencaa/jiujia] 点击开始没有反应 (Issue #1)




 
现在只是TK  好像不行了 要类似这一段了
 Host: wx.scmttec.com
 Connection: keep-alive
 Accept: application/json, text/plain, /
 tk: wxtoken:f9bd4e1a111df01c530a79b30063f9c6_0ef94d2f3ffbb43b470c6663291c3d97
 User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 NetType/WIFI MicroMessenger/7.0.20.1781(0x6700143B) WindowsWechat(0x63060012)
 st: af813f3b3ae8ae30da42bcab610c602e
 
&mdash;

**Comment by rencaa** [comment]
抓域名是这个的啊 wx.scmttec.com

**Comment by hllhe** [comment]
确实发现了，正在调整方向，感谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rencaa/jiujia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 晚上10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rencaa/jiujia] 点击开始没有反应 (Issue #1)





 
抓域名是这个的啊 wx.scmttec.com

**Comment by hllhe** [comment]
Accept: application/json, text/plain, */*
tk: wxtoken:0c260a59cad55********************_cd1d5b21c12fd5b612272d04ac91d5d6
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 NetType/WIFI MicroMessenger/7.0.20.1781(0x6700143B) WindowsWechat(0x63060012)
st: 5ff6658cf5d**************21acdc6f96c
Cookie: UM_distinctid=**************59e258c8c35-61273a23-146d15-1804228920167a; CNZZDATA1261985103=1149815051-165*********63; _xzkj_=wxtoken:0c260a*************da1340a5_cd1d5b***********2272d04ac91d5d6; _xxhm_=%7B%22id%22%3A17012385%2C%22openId%22%3A%22o********%22%2C%22unionid%22%3A%22o********%22%2C%22mobile*******************************%22%3A%22%E5%9C%A8%E6%88%91%E7%9C%BC%E9%87%8C%E4%BD%A0%E4%BC%9A%E5%8F%91%E5%85%89%22%2C%22headerImg%22%3A%22https%3A%2F%2Fthirdwx.qlogo.cn%2Fmmopen%2Fvi_32%2FjO2jcU8qMUE4ccmSg1V38PnO6Yz2iajSK6kAev5joHboSGsIjVJb2hY8Zo1nKStexIoVp8j6W3XKRCGUbmfIbnA%2F132%22%2C%22regionCod****************************************************************************888*%22birthday%22%3A%222001-10-
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://wx.scmttec.com/index.html
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7



这次已经找到，点击开始依然没有反应，不知道在哪里查看结果


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rencaa/jiujia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 晚上10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rencaa/jiujia] 点击开始没有反应 (Issue #1)





 
抓域名是这个的啊 wx.scmttec.com

**Comment by rencaa** [comment]
数字在变化就说明在运行  自行配置通知系统的token   如果有新开的会微信通知

**Comment by rencaa** [comment]
数字如果没有循环变化，就说明没有成功运行.建议晚上不要开

**Comment by hllhe** [comment]
目前没有任何东西显示


明白了，谢谢老哥的回复，我后面有空再试试


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rencaa/jiujia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 晚上10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rencaa/jiujia] 点击开始没有反应 (Issue #1)





 
数字如果没有循环变化，就说明没有成功运行.建议晚上不要开

**Comment by DY2434** [comment]
只用输入tk内容吗？还是上面说的要抓的包都要输入？

**Comment by rencaa** [comment]
> 只用输入tk内容吗？还是说的要抓的包全部输入？
全部

**Comment by rencaa** [comment]
> 

全部

**Comment by DY2434** [comment]
换了地区代码又不运行了
